/**
 * Comprehensive list of disposable/temporary email domains.
 * Used to block sign-ups with throwaway addresses.
 */
const TEMP_DOMAINS: ReadonlySet<string> = new Set([
  // Major disposable email services
  'tempmail.com', 'temp-mail.org', 'temp-mail.io', 'tempail.com',
  'guerrillamail.com', 'guerrillamail.net', 'guerrillamail.org', 'guerrillamail.de', 'guerrillamail.biz',
  'guerrillamailblock.com', 'grr.la', 'sharklasers.com', 'guerrilla.ml',
  '10minutemail.com', '10minutemail.net', '10minutemail.org', '10minute.email',
  'yopmail.com', 'yopmail.fr', 'yopmail.net', 'yopmail.gq',
  'mailinator.com', 'mailinator.net', 'mailinator.org', 'mailinator2.com',
  'throwaway.email', 'throwaway.com',
  'maildrop.cc', 'maildrop.ml',
  'dispostable.com',
  'mailnesia.com',
  'getnada.com', 'nada.email',
  'mohmal.com', 'mohmal.in', 'mohmal.tech',
  'tempinbox.com',
  'trashmail.com', 'trashmail.me', 'trashmail.net', 'trashmail.org', 'trashmail.io',
  'trashinbox.com',
  'fakeinbox.com', 'fakemail.net',
  'discard.email', 'discardmail.com', 'discardmail.de',
  'emailondeck.com',
  'tempmailaddress.com',
  'tempmailo.com',
  'harakirimail.com',
  'mintemail.com',
  'mytemp.email',
  'binkmail.com',
  'bobmail.info',
  'chammy.info',
  'devnullmail.com',
  'disbox.net', 'disbox.org',
  'disposeamail.com',
  'dodgeit.com',
  'dodgit.com',
  'dontreg.com',
  'e4ward.com',
  'emailigo.de',
  'emailisvalid.com',
  'emailresort.com',
  'emailtemporanea.com', 'emailtemporanea.net',
  'emailwarden.com',
  'emz.net',
  'enterto.com',
  'ephemail.net',
  'etranquil.com', 'etranquil.net', 'etranquil.org',
  'fakemailgenerator.com',
  'fastacura.com',
  'filzmail.com',
  'fixmail.tk',
  'flyspam.com',
  'getairmail.com',
  'getonemail.com', 'getonemail.net',
  'girlsundertheinfluence.com',
  'gishpuppy.com',
  'great-host.in',
  'greensloth.com',
  'gsrv.co.uk',
  'haltospam.com',
  'hotpop.com',
  'ichimail.com',
  'imails.info',
  'inboxalias.com',
  'inboxclean.com', 'inboxclean.org',
  'incognitomail.com', 'incognitomail.net', 'incognitomail.org',
  'jetable.com', 'jetable.fr.nf', 'jetable.net', 'jetable.org',
  'kasmail.com',
  'koszmail.pl',
  'kurzepost.de',
  'letthemeatspam.com',
  'lhsdv.com',
  'lifebyfood.com',
  'link2mail.net',
  'litedrop.com',
  'lookugly.com',
  'lopl.co.cc',
  'lortemail.dk',
  'lr78.com',
  'lroid.com',
  'lukop.dk',
  'mailbidon.com',
  'mailblocks.com',
  'mailbucket.org',
  'mailcatch.com',
  'maileater.com',
  'mailexpire.com',
  'mailforspam.com',
  'mailfreeonline.com',
  'mailguard.me',
  'mailin8r.com',
  'mailinater.com',
  'mailincubator.com',
  'mailismagic.com',
  'mailmate.com',
  'mailme.ir', 'mailme.lv',
  'mailmetrash.com',
  'mailmoat.com',
  'mailms.com',
  'mailnator.com',
  'mailnull.com',
  'mailorg.org',
  'mailpick.biz',
  'mailproxsy.com',
  'mailquack.com',
  'mailrock.biz',
  'mailscrap.com',
  'mailshell.com',
  'mailsiphon.com',
  'mailslapping.com',
  'mailslite.com',
  'mailtemp.info',
  'mailtothis.com',
  'mailtrash.net',
  'mailzilla.com', 'mailzilla.org',
  'mbx.cc',
  'mega.zik.dj',
  'meltmail.com',
  'messagebeamer.de',
  'mezimages.net',
  'mfsa.ru', 'mfsa.info',
  'ministry-of-silly-walks.de',
  'moburl.com',
  'moncourrier.fr.nf',
  'monemail.fr.nf',
  'monmail.fr.nf',
  'mt2015.com',
  'mx0.wwwnew.eu',
  'mypartyclip.de',
  'myphantom.com',
  'mysamp.de',
  'myspaceinc.com', 'myspaceinc.net', 'myspaceinc.org',
  'myspacepimpedup.com',
  'mytrashmail.com',
  'neomailbox.com',
  'nepwk.com',
  'nervmich.net',
  'nervtansen.de',
  'netmails.com', 'netmails.net',
  'netzidiot.de',
  'neverbox.com',
  'no-spam.ws',
  'nobulk.com',
  'noclickemail.com',
  'nogmailspam.info',
  'nomail.xl.cx',
  'nomail2me.com',
  'nomorespamemails.com',
  'nospam.ze.tc', 'nospam4.us',
  'nospamfor.us', 'nospammail.net',
  'nothingtoseehere.ca',
  'nowmymail.com',
  'nurfuerspam.de',
  'nus.edu.sg',
  'objectmail.com',
  'obobbo.com',
  'onewaymail.com',
  'oopi.org',
  'ordinaryamerican.net',
  'otherinbox.com',
  'ourklips.com',
  'outlawspam.com',
  'ovpn.to',
  'owlpic.com',
  'pancakemail.com',
  'pimpedupmyspace.com',
  'pjjkp.com',
  'plexolan.de',
  'pookmail.com',
  'privacy.net',
  'proxymail.eu',
  'prtnx.com',
  'punkass.com',
  'putthisinyouspam.com',
  'qq.com',
  'quickinbox.com',
  'rcpt.at',
  'reallymymail.com',
  'recode.me',
  'recursor.net',
  'regbypass.com', 'regbypass.comsafe-mail.net',
  'rejectmail.com',
  'reliable-mail.com',
  'rhyta.com',
  'rklips.com',
  'rmqkr.net',
  'royal.net',
  'rppkn.com',
  'rtrtr.com',
  's0ny.net',
  'safe-mail.net',
  'safersignup.de',
  'safetymail.info',
  'safetypost.de',
  'sandelf.de',
  'saynotospams.com',
  'scatmail.com',
  'schafmail.de',
  'selfdestructingmail.com',
  'sendspamhere.com',
  'sharklasers.com',
  'shieldedmail.com',
  'shiftmail.com',
  'shitmail.me', 'shitmail.org',
  'shortmail.net',
  'sibmail.com',
  'skeefmail.com',
  'slaskpost.se',
  'slipry.net',
  'slopsbox.com',
  'smashmail.de',
  'soodonims.com',
  'spam.la', 'spam.su', 'spam4.me',
  'spamavert.com',
  'spambob.com', 'spambob.net', 'spambob.org',
  'spambog.com', 'spambog.de', 'spambog.ru',
  'spambox.us',
  'spamcannon.com', 'spamcannon.net',
  'spamcero.com',
  'spamcorptastic.com',
  'spamcowboy.com', 'spamcowboy.net', 'spamcowboy.org',
  'spamday.com',
  'spamex.com',
  'spamfighter.cf', 'spamfighter.ga', 'spamfighter.gq', 'spamfighter.ml', 'spamfighter.tk',
  'spamfree24.com', 'spamfree24.de', 'spamfree24.eu', 'spamfree24.info', 'spamfree24.net', 'spamfree24.org',
  'spamgoes.in',
  'spamherelots.com', 'spamhereplease.com',
  'spamhole.com',
  'spamify.com',
  'spaminator.de',
  'spamkill.info',
  'spaml.com', 'spaml.de',
  'spammotel.com',
  'spamobox.com',
  'spamoff.de',
  'spamslicer.com',
  'spamspot.com',
  'spamstack.net',
  'spamthis.co.uk',
  'spamthisplease.com',
  'spamtrail.com',
  'spamtrap.ro',
  'speed.1s.fr',
  'superrito.com',
  'suremail.info',
  'svk.jp',
  'sweetxxx.de',
  'tafmail.com',
  'tagyoureit.com',
  'teleworm.com', 'teleworm.us',
  'temp.emeraldcraft.com',
  'temp.headstrong.de',
  'tempalias.com',
  'tempe4mail.com',
  'tempemail.biz', 'tempemail.co.za', 'tempemail.com', 'tempemail.net',
  'tempinbox.co.uk', 'tempinbox.com',
  'tempmail.eu', 'tempmail.it', 'tempmail2.com',
  'tempmailer.com', 'tempmailer.de',
  'tempomail.fr',
  'temporarily.de',
  'temporarioemail.com.br',
  'temporaryemail.net', 'temporaryemail.us',
  'temporaryforwarding.com',
  'temporaryinbox.com',
  'temporarymailaddress.com',
  'thanksnospam.info',
  'thankyou2010.com',
  'thc.st',
  'thelimestones.com',
  'thisisnotmyrealemail.com',
  'thismail.net', 'thismail.ru',
  'thrma.com',
  'throwawayemailaddress.com',
  'tittbit.in',
  'tmail.ws',
  'tmailinator.com',
  'toiea.com',
  'toomail.biz',
  'topranklist.de',
  'tradermail.info',
  'trash-amil.com', 'trash-mail.at', 'trash-mail.com', 'trash-mail.de',
  'trash2009.com', 'trash2010.com', 'trash2011.com',
  'trashdevil.com', 'trashdevil.de',
  'trashemail.de',
  'trashemails.de',
  'trashymail.com', 'trashymail.net',
  'trbvm.com', 'trbvn.com',
  'trialmail.de',
  'trickmail.net',
  'trillianpro.com',
  'turual.com',
  'twinmail.de',
  'tyldd.com',
  'uggsrock.com',
  'umail.net',
  'upliftnow.com',
  'uplipht.com',
  'venompen.com',
  'veryreallymymail.com',
  'viditag.com',
  'viewcastmedia.com', 'viewcastmedia.net', 'viewcastmedia.org',
  'vomoto.com',
  'vpn.st',
  'vsimcard.com',
  'vubby.com',
  'wasteland.rfc822.org',
  'webemail.me',
  'weg-werf-email.de',
  'wegwerfadresse.de',
  'wegwerfemail.com', 'wegwerfemail.de',
  'wegwerfmail.de', 'wegwerfmail.net', 'wegwerfmail.org',
  'wh4f.org',
  'whatiaas.com',
  'whatpaas.com',
  'whyspam.me',
  'wikidocuslice.com',
  'willhackforfood.biz',
  'willselfdestruct.com',
  'winemaven.info',
  'wronghead.com',
  'wuzup.net', 'wuzupmail.net',
  'wwwnew.eu',
  'xagloo.com',
  'xemaps.com',
  'xents.com',
  'xjoi.com',
  'xmaily.com',
  'xoxy.net',
  'yep.it',
  'yogamaven.com',
  'yuurok.com',
  'zehnminutenmail.de',
  'zippymail.info',
  'zoaxe.com',
  'zoemail.org',
  // Additional commonly used disposable services
  'mailcatch.com', 'mail-temporaire.fr', 'crazymailing.com',
  'mailsac.com', 'inboxkitten.com', 'burnermail.io',
  'sharklasers.com', 'tempail.com', 'emailfake.com',
  'emaillime.com', 'emailsensei.com', 'fakedemail.com',
  'armyspy.com', 'cuvox.de', 'dayrep.com', 'einrot.com',
  'fleckens.hu', 'gustr.com', 'jourrapide.com', 'superrito.com',
]);

/**
 * Check if an email address uses a known disposable/temporary email domain.
 * @returns true if the email domain is a known disposable provider.
 */
export function isTempEmail(email: string): boolean {
  if (!email || !email.includes('@')) return false;
  const domain = email.split('@')[1]?.toLowerCase().trim();
  if (!domain) return false;
  return TEMP_DOMAINS.has(domain);
}
